### ISSUE TITLE
Please add support for a single page application

### ISSUE THREAD

**Issue by mikeblakeuk** [endjin/Endjin.SpecFlow.Selenium#3]
Would it be possible to suggest how to break up a single page application (e.g. the URL isn't changing)

``` C#
this.AddPage<MassiveSinglePageModel>(Page.Home, string.Empty);
```

**Comment by HowardvanRooijen** [comment]
How does your SPA signify changing state - does it use anchor tags or hash-bangs?

**Comment by mikeblakeuk** [comment]
via @neilrees; "ng-route and hash-slash routing".

I guess I'm looking to break up the Views and Models even tho they could exist as one.

``` C#
this.AddPage<ImportPackagePageModel>()
this.AddPage<RunJobPageModel>()
```

**Comment by mikeblakeuk** [comment]
Hi guys. We've ended up using our own selenium framework. Thanks anyways.
